version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: development
    command: make dev

