version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: imollyj/devops-for-programmers-project-74
    ports:
      - "8080:8080"
    container_name: app
    command: bash -c "sleep 5 && npm test"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE-PORT: 5432

  db:
    image: postgres:16.3
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

