version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: imollyj/devops-for-programmers-project-74
    ports:
      - "8080:8080"
    container_name: app
    working_dir: /app
    command: bash -c "sleep 5 && npm test"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE-PORT=5432
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

