name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  ci-build:
    name: Run Tests and Build Docker Image
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Installation Docker Compose
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Verify Docker Compose Installation
      run: docker-compose --version

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3 Run tests with Docker Compose
    - name: Run tests
      run:  docker-compose -f docker-compose.yml up --abort-on-container-exit

    # 4. Deploy production
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.production
        push: true
        tags: mollyj/devops-for-programmers-project-74:latest

